version: '3'

services:
  myredis:
    image: "redis:alpine"
    volumes:
      - ./redis:/home
    ports:
      - "6379:6379"
  web:
    build:
      context: flask/
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"
    depends_on:
      - myredis

volumes:
  redis: