apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-ai-cal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-ai-cal
  template:
    metadata:
      labels:
        app: team-ai-cal
    spec:
      containers:
      - name: team-ai-cal
        image: ywlee/my-team-calendar:v1.5
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: psql-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: psql-secret
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: psql-secret
              key: POSTGRES_PORT
        - name: POSTGRES_DB_NAME
          valueFrom:
            secretKeyRef:
              name: psql-secret
              key: POSTGRES_DB_NAME
        - name: DJANGO_USER
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DJANGO_USER
        - name: DJANGO_PASS
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DJANGO_PASS
        command: ["/home/proj/scripts/init.sh"]
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: team-ai-cal
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: team-ai-cal

