version: '3'

services:
  mydb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dj
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    links:
      - mydb
    # env_file:
    #   - ./grafana/config.monitoring
    # volumes:
    #   - ./grafana/dashboard:/etc/extra-config/grafana
    # command: ./etc/extra-config/grafana/post.sh
    depends_on:
      - mydb
